project_id = "ddbpzfchbihvzqsoybsx"

[functions.financial-analysis]
verify_jwt = false

[functions.process-document]
verify_jwt = false

[functions.rag-query]
verify_jwt = false

[functions.log-interaction]
verify_jwt = false

[functions.get-few-shot-examples]
verify_jwt = false

[functions.admin]
verify_jwt = false

[functions.send-email]
verify_jwt = false