import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { FileDown, Loader2, CheckCircle } from "lucide-react";
import { toast } from "sonner";

interface ReportExportProps {
  analysisText: string;
  analysisType: string;
}

export default function ReportExport({ analysisText, analysisType }: ReportExportProps) {
  const [isExporting, setIsExporting] = useState(false);
  const [exported, setExported] = useState(false);

  const generatePDFReport = async () => {
    if (!analysisText) {
      toast.error("No analysis data to export");
      return;
    }

    setIsExporting(true);
    try {
      // Build a styled HTML document for printing
      const reportDate = new Date().toLocaleDateString("en-US", {
        year: "numeric", month: "long", day: "numeric",
      });

      const cleanText = analysisText
        .replace(/\|/g, " | ")
        .replace(/#{1,3}\s*/g, "")
        .split("\n")
        .map((line) => {
          if (line.startsWith("**") && line.endsWith("**")) {
            return `<h3 style="color:#2563eb;margin:16px 0 8px;font-size:14px;">${line.replace(/\*\*/g, "")}</h3>`;
          }
          if (line.includes("|") && line.includes("---")) return "";
          if (line.includes("|")) {
            const cells = line.split("|").filter(Boolean).map((c) => c.trim());
            return `<tr>${cells.map((c) => `<td style="padding:6px 12px;border:1px solid #e5e7eb;font-size:11px;">${c}</td>`).join("")}</tr>`;
          }
          if (line.trim() === "") return "<br/>";
          return `<p style="margin:4px 0;font-size:12px;line-height:1.6;color:#374151;">${line}</p>`;
        })
        .join("\n");

      // Wrap table rows
      const withTables = cleanText.replace(
        /(<tr>[\s\S]*?<\/tr>(?:\s*<tr>[\s\S]*?<\/tr>)*)/g,
        '<table style="width:100%;border-collapse:collapse;margin:12px 0;">$1</table>'
      );

      const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>FinalyzeAI Report</title>
  <style>
    @media print {
      body { margin: 0; padding: 20px; }
      .no-print { display: none; }
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px;
      color: #1f2937;
    }
    .header {
      border-bottom: 3px solid #2563eb;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .header h1 {
      font-size: 24px;
      color: #2563eb;
      margin: 0 0 4px;
    }
    .header p {
      color: #6b7280;
      font-size: 12px;
      margin: 2px 0;
    }
    .badge {
      display: inline-block;
      background: #eff6ff;
      color: #2563eb;
      padding: 4px 12px;
      border-radius: 20px;
      font-size: 11px;
      font-weight: 600;
      margin-top: 8px;
    }
    .footer {
      margin-top: 40px;
      padding-top: 16px;
      border-top: 1px solid #e5e7eb;
      font-size: 10px;
      color: #9ca3af;
      text-align: center;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>FinalyzeAI</h1>
    <p>Financial Analysis Report</p>
    <p>Generated: ${reportDate}</p>
    <span class="badge">${analysisType.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase())}</span>
  </div>
  <div class="content">
    ${withTables}
  </div>
  <div class="footer">
    <p>Generated by FinalyzeAI — AI-Powered Financial Analysis Platform</p>
    <p>This report is for informational purposes only and does not constitute financial advice.</p>
  </div>
  <script class="no-print">
    window.onload = function() { window.print(); }
  </script>
</body>
</html>`;

      // Open print dialog
      const printWindow = window.open("", "_blank");
      if (printWindow) {
        printWindow.document.write(htmlContent);
        printWindow.document.close();
        setExported(true);
        toast.success("Report ready! Use the print dialog to save as PDF.");
        setTimeout(() => setExported(false), 3000);
      } else {
        // Fallback: download as HTML
        const blob = new Blob([htmlContent], { type: "text/html" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `finalyzeai-report-${Date.now()}.html`;
        a.click();
        URL.revokeObjectURL(url);
        toast.success("Report downloaded! Open and print to save as PDF.");
      }
    } catch (error) {
      console.error("Export error:", error);
      toast.error("Failed to generate report");
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <Card className="border-border/30 bg-card/50">
      <CardContent className="py-3 px-4">
        <div className="flex items-center justify-between gap-3">
          <div className="flex items-center gap-2 min-w-0">
            <FileDown className="w-4 h-4 text-primary shrink-0" />
            <span className="text-sm text-foreground font-medium truncate">Export Report</span>
          </div>
          <Button
            variant="outline"
            size="sm"
            onClick={generatePDFReport}
            disabled={isExporting || !analysisText}
            className="h-8 text-xs gap-1.5 shrink-0"
          >
            {isExporting ? (
              <><Loader2 className="w-3 h-3 animate-spin" /> Generating...</>
            ) : exported ? (
              <><CheckCircle className="w-3 h-3 text-emerald-400" /> Exported</>
            ) : (
              <><FileDown className="w-3 h-3" /> Save as PDF</>
            )}
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
