// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.1";

// src/lib/mcp/tools/list-documents.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.87.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-documents.ts
var list_documents_default = defineTool({
  name: "list_documents",
  title: "List documents",
  description: "List the signed-in user's uploaded financial documents in FinalyzeAI.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max documents to return (default 20)."),
    status: z.string().optional().describe("Optional status filter, e.g. 'completed'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("documents").select("id, name, file_type, file_size, status, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { documents: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-documents.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z2 } from "npm:zod@^3.25.76";
var search_documents_default = defineTool2({
  name: "search_documents",
  title: "Search document content",
  description: "Keyword-search the text chunks of the signed-in user's uploaded documents in FinalyzeAI and return matching excerpts.",
  inputSchema: {
    query: z2.string().min(2).describe("Keyword or phrase to search for."),
    document_id: z2.string().uuid().optional().describe("Optional document id to restrict the search."),
    limit: z2.number().int().min(1).max(20).optional().describe("Max excerpts to return (default 8).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, document_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("document_chunks").select("id, document_id, chunk_index, content").ilike("content", `%${query.replace(/[%_]/g, "")}%`).order("chunk_index", { ascending: true }).limit(limit ?? 8);
    if (document_id) q = q.eq("document_id", document_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const excerpts = (data ?? []).map((row) => ({
      ...row,
      content: typeof row.content === "string" ? row.content.slice(0, 1200) : row.content
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(excerpts) }],
      structuredContent: { excerpts }
    };
  }
});

// src/lib/mcp/tools/list-analyses.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_analyses_default = defineTool3({
  name: "list_analyses",
  title: "List AI analyses",
  description: "List the signed-in user's recent FinalyzeAI analyses (query, analysis type, rating and response excerpt).",
  inputSchema: {
    limit: z3.number().int().min(1).max(30).optional().describe("Max analyses to return (default 10)."),
    analysis_type: z3.string().optional().describe("Optional analysis type filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, analysis_type }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("interactions").select("id, query, response, rating, analysis_type, created_at").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (analysis_type) q = q.eq("analysis_type", analysis_type);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const analyses = (data ?? []).map((row) => ({
      ...row,
      response: typeof row.response === "string" ? row.response.slice(0, 2e3) : row.response
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(analyses) }],
      structuredContent: { analyses }
    };
  }
});

// src/lib/mcp/tools/list-conversations.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_conversations_default = defineTool4({
  name: "list_conversations",
  title: "List conversations",
  description: "List the signed-in user's FinalyzeAI chat conversations, optionally including the messages of one conversation.",
  inputSchema: {
    conversation_id: z4.string().uuid().optional().describe("If provided, return the messages of this conversation instead of the list."),
    limit: z4.number().int().min(1).max(50).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ conversation_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    if (conversation_id) {
      const { data: data2, error: error2 } = await supabase.from("conversation_messages").select("id, role, content, created_at").eq("conversation_id", conversation_id).order("created_at", { ascending: true }).limit(limit ?? 20);
      if (error2) return { content: [{ type: "text", text: error2.message }], isError: true };
      return {
        content: [{ type: "text", text: JSON.stringify(data2 ?? []) }],
        structuredContent: { messages: data2 ?? [] }
      };
    }
    const { data, error } = await supabase.from("conversations").select("id, title, created_at, updated_at").order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { conversations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-account-summary.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.1";
var get_account_summary_default = defineTool5({
  name: "get_account_summary",
  title: "Get account summary",
  description: "Get the signed-in user's FinalyzeAI plan, usage limits and document/analysis counts.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const [plan, docs, analyses] = await Promise.all([
      supabase.from("user_plans").select("plan_name, upload_limit_mb, history_retention_days, daily_limit, monthly_limit, started_at, expires_at").maybeSingle(),
      supabase.from("documents").select("id", { count: "exact", head: true }),
      supabase.from("interactions").select("id", { count: "exact", head: true })
    ]);
    const firstError = plan.error ?? docs.error ?? analyses.error;
    if (firstError) {
      return { content: [{ type: "text", text: firstError.message }], isError: true };
    }
    const summary = {
      email: ctx.getUserEmail() ?? null,
      plan: plan.data ?? { plan_name: "free" },
      document_count: docs.count ?? 0,
      analysis_count: analyses.count ?? 0
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ddbpzfchbihvzqsoybsx";
var mcp_default = defineMcp({
  name: "finalyze-ai-navigator",
  title: "Finance AI Navigator",
  version: "0.1.0",
  instructions: "Tools for FinalyzeAI, an AI financial analysis platform. Use `list_documents` and `search_documents` to explore the user's uploaded financial documents, `list_analyses` for past AI analyses, `list_conversations` for chat history, and `get_account_summary` for plan and usage details. All tools act as the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_documents_default,
    search_documents_default,
    list_analyses_default,
    list_conversations_default,
    get_account_summary_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
