import { useState } from "react";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { CheckCircle, FileDown, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";

export interface PdfRow {
  label: string;
  value: string;
}

interface PdfResultCaptureProps {
  /** Short machine name of the tool, e.g. "runway" */
  source: string;
  /** Human title used in the PDF header, e.g. "Burn Rate & Runway" */
  title: string;
  rows: PdfRow[];
  note?: string;
}

const emailSchema = z
  .string()
  .trim()
  .min(5, { message: "Enter a valid email address" })
  .max(255, { message: "Email must be less than 255 characters" })
  .email({ message: "Enter a valid email address" });

const escapeHtml = (s: string) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

const buildHtml = (title: string, rows: PdfRow[], note?: string) => {
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const body = rows
    .map(
      (r) => `<tr>
        <td style="padding:10px 0;border-bottom:1px solid #e5e7eb;font-size:13px;color:#374151;">${escapeHtml(r.label)}</td>
        <td style="padding:10px 0;border-bottom:1px solid #e5e7eb;font-size:13px;font-weight:600;text-align:right;font-family:ui-monospace,Menlo,monospace;color:#111827;">${escapeHtml(r.value)}</td>
      </tr>`,
    )
    .join("");

  return `<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>FinalyzeAI — ${escapeHtml(title)}</title>
<style>
  body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:760px;margin:0 auto;padding:48px 40px;color:#1f2937;}
  h1{font-size:22px;color:#2563eb;margin:0 0 4px;}
  h2{font-size:16px;margin:28px 0 8px;color:#111827;}
  .meta{color:#6b7280;font-size:12px;margin:2px 0;}
  .header{border-bottom:3px solid #2563eb;padding-bottom:18px;margin-bottom:24px;}
  table{width:100%;border-collapse:collapse;}
  .note{margin-top:20px;font-size:12px;line-height:1.6;color:#4b5563;}
  .footer{margin-top:40px;padding-top:14px;border-top:1px solid #e5e7eb;font-size:10px;color:#9ca3af;text-align:center;}
  @media print{body{padding:24px;}}
</style></head>
<body>
  <div class="header">
    <h1>FinalyzeAI</h1>
    <p class="meta">${escapeHtml(title)} — result report</p>
    <p class="meta">Generated: ${date}</p>
  </div>
  <h2>Your results</h2>
  <table>${body}</table>
  ${note ? `<p class="note">${escapeHtml(note)}</p>` : ""}
  <p class="note">Run more free financial calculators at finalyzeai.com/calculators, or upload a real
  statement to AI Predict for a full ratio and risk breakdown.</p>
  <div class="footer">
    <p>Generated by FinalyzeAI — AI-Powered Financial Analysis</p>
    <p>For informational purposes only; not financial advice.</p>
  </div>
  <script>window.onload=function(){window.print();}</script>
</body></html>`;
};

const PdfResultCapture = ({ source, title, rows, note }: PdfResultCaptureProps) => {
  const [email, setEmail] = useState("");
  const [loading, setLoading] = useState(false);
  const [done, setDone] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const parsed = emailSchema.safeParse(email);
    if (!parsed.success) {
      toast.error(parsed.error.issues[0].message);
      return;
    }

    setLoading(true);
    try {
      const { error } = await supabase.from("email_leads").insert({
        email: parsed.data.toLowerCase(),
        source,
        result_summary: rows as unknown as never,
        page_path: window.location.pathname,
      } as never);
      if (error) throw error;

      const html = buildHtml(title, rows, note);
      const win = window.open("", "_blank");
      if (win) {
        win.document.write(html);
        win.document.close();
        toast.success("Report ready — save it as PDF from the print dialog.");
      } else {
        const blob = new Blob([html], { type: "text/html" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `finalyzeai-${source}-report.html`;
        a.click();
        URL.revokeObjectURL(url);
        toast.success("Report downloaded — open it and print to PDF.");
      }
      setDone(true);
    } catch (err) {
      console.error("Lead capture failed:", err);
      toast.error("Could not generate the report. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  if (done) {
    return (
      <div className="flex items-center gap-2 rounded-lg border border-border/50 bg-muted/30 px-3 py-2.5 text-sm">
        <CheckCircle className="w-4 h-4 text-primary shrink-0" />
        <span className="text-muted-foreground">
          Report generated. We&apos;ll send occasional founder finance tips — unsubscribe anytime.
        </span>
      </div>
    );
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-2 rounded-lg border border-border/50 bg-muted/20 p-3">
      <p className="text-xs font-medium text-foreground">Email me this result as a PDF</p>
      <div className="flex flex-col sm:flex-row gap-2">
        <Input
          type="email"
          inputMode="email"
          autoComplete="email"
          maxLength={255}
          placeholder="you@company.com"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          className="h-9 text-sm"
          required
        />
        <Button type="submit" size="sm" className="h-9 gap-1.5 shrink-0" disabled={loading}>
          {loading ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <FileDown className="w-3.5 h-3.5" />}
          Get PDF
        </Button>
      </div>
      <p className="text-[11px] leading-snug text-muted-foreground">
        We only use your email to send this report and occasional finance tips. No spam.
      </p>
    </form>
  );
};

export default PdfResultCapture;
